print('Welcome to my first progam in Python')
print('My favourite hobby is Football')
print('Did you know Python can do calculation? The line of code below will display the the number 10')
print(7+3)
print('How about this? the calculation below should display the number 18')
print(7+3*2+5)
print('My name is Aryan')
print('My favourite number is 7')
print('My favourite players are Ronaldo and Messi')
print(12831+129)
